language: node_js
node_js:
  - "8"
  - "10"
  - "12"
addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - xvfb
env:
  global:
    - CXX=g++-4.8
    - DISPLAY=:99.0
  matrix:
    - CXX=g++-4.8 TEST_SUITE=test:node
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "8"
      env: CXX=g++-4.8 TEST_SUITE=coveralls
    - os: linux
      node_js: "8"
      env: CXX=g++-4.8 TEST_SUITE=lint
    - os: linux
      node_js: "8"
      env: CXX=g++-4.8 TEST_SUITE=test:node
    - os: linux
      node_js: "8"
      env: CXX=g++-4.8 TEST_SUITE=test:node
    - os: linux
      node_js: "10"
      env: CXX=g++-4.8 TEST_SUITE=test:node
    - os: linux
      node_js: "12"
      env: CXX=g++-4.8 TEST_SUITE=test:node

script: npm run $TEST_SUITE
