name: Account
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-account:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 13, 14]
    env:
      cwd: ${{github.workspace}}/packages/account
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1

      - run: npx lerna bootstrap --scope ethereumjs-account --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run build --scope ethereumjs-account --include-dependencies
      - run: npx lerna run lint --scope ethereumjs-account

      - run: npx lerna run coverage --scope ethereumjs-account

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: account
        if: ${{ matrix.node-version == 12 }}
