name: Blockchain
'on':
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - packages/account/**
      - packages/block/**
      - packages/common/**
      - packages/tx/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - packages/account/**
      - packages/block/**
      - packages/common/**
      - packages/tx/**
jobs:
  test-blockchain:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-blockchain --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-blockchain --include-dependencies build
      - run: npx lerna run lint --scope ethereumjs-blockchain
      - run: npm test
        working-directory: '${{ env.cwd }}'
      - uses: codecov/codecov-action@v1
        with:
          file: '${{ env.cwd }}/coverage/lcov.info'
          flags: blockchain
    env:
      cwd: '${{github.workspace}}/packages/blockchain'
