name: Block
'on':
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - packages/account/**
      - packages/common/**
      - packages/tx/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - packages/account/**
      - packages/common/**
      - packages/tx/**
jobs:
  test-block:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v1
      - run: npm install
          working-directory: '${{ env.cwd }}'
      - run: npm run lint
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
      - run: 'npm run test:node'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
      - run: 'npm run test:browser'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/block'
  