name: Browser
on:
  push:
    branches: [master, develop]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  test-all-browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # necessary for block tests to load ethereum/tests
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run install-browser-deps

      - run: npm run test:browser -w=@ethereumjs/rlp
      - run: npm run test:browser -w=@ethereumjs/util
      - run: npm run test:browser -w=@ethereumjs/common
      - run: npm run test:browser -w=@ethereumjs/trie
      - run: npm run test:browser -w=@ethereumjs/tx
      - run: npm run test:browser -w=@ethereumjs/block
      #     No browser tests for devp2p
      - run: npm run test:browser -w=@ethereumjs/blockchain
      #     No browser tests for ethash
      - run: npm run test:browser -w=@ethereumjs/wallet
      - run: npm run test:browser -w=@ethereumjs/statemanager
      - run: npm run test:browser -w=@ethereumjs/evm
      - run: npm run test:browser -w=@ethereumjs/vm

