name: Common
on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - packages/account/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - packages/account/**
jobs:
  test-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 13, 14]
    env:
      cwd: ${{github.workspace}}/packages/common
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-common --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-common --include-dependencies build
      - run: npx lerna run lint --scope ethereumjs-common
      - run: npm test
        working-directory: ${{ env.cwd }}

      - run: npm run coverage
        working-directory: ${{ env.cwd }}
        if: ${{ matrix.node-version == 12
      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: common
        if: ${{ matrix.node-version == 12
