name: E2E
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}

jobs:
  virtual-npm-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          key: E2E-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          path: '**/node_modules'

      # Installs all dependencies, bootstrapping everything.
      - run: npm install
        if: steps.cache.outputs.cache-hit != 'true'

      # Publishes all packages to a virtual npm registry after giving each a minor version bump
      - name: Publish to virtual registry
        run: npm run e2e:publish

      # This project is simple / does not require resolutions injection
      - name: E2E Target - NoahZinsmeister/as-you-permit
        run: |
          rm -rf as-you-permit
          git clone https://github.com/NoahZinsmeister/as-you-permit.git
          cd as-you-permit
          yarn
          rm -rf dist
          yarn remove @ethereumjs/vm
          yarn add @ethereumjs/vm@e2e
          yarn test --verbose
        env:
          URL_MAINNET: ${{ secrets.URL_MAINNET }}
