# This special file aims to run node tests for each relevant node version.
# A relevant node version can be: active, current, maintenance or EOL with some months of tolerance
# For more details, please check ./scripts/node-versions.js
name: Node versions
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  get-node-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - id: set-matrix
        run: echo "::set-output name=matrix::$(npx testable-node-versions)"

  tests:
    needs: get-node-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{ fromJson(needs.get-node-versions.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Use npm v7 for workspaces support
        run: npm i -g npm@7
        if: ${{ matrix.node-version < 16 }}

      - run: npm i

      - name: Test Block
        run: npm run test
        working-directory: packages/block

      - name: Test Blockchain
        run: npm run test
        working-directory: packages/blockchain

      # Client and Devp2p temporarily disabled for Node < 15 due to browser build
      # error along node-versions CI run "TextDecoder is not defined" triggered in
      # older Noder versions (Node 12/14)
      # https://github.com/ethereumjs/ethereumjs-monorepo/pull/1305
      # 2021-06-18
      #
      # TODO: give this another test run in times and reactivate (note that this
      # might also be an issue which gets fixed downstream at some point in time)
      - name: Test Client
        run: npm run test
        working-directory: packages/client
        if: ${{ matrix.node >= 15 }}

      - name: Test Devp2p
        run: npm run test
        working-directory: packages/devp2p
        if: ${{ matrix.node >= 15 }}

      - name: Test Common
        run: npm run test
        working-directory: packages/common

      - name: Test Ethash
        run: npm run test
        working-directory: packages/ethash

      - name: Test Trie
        run: npm run test
        working-directory: packages/trie

      - name: Test Tx
        run: npm run test
        working-directory: packages/tx

      - name: Test Util
        run: npm run test
        working-directory: packages/util

      - name: Test StateManager
        run: npm run test:API
        working-directory: packages/statemanager

      - name: Test VM
        run: npm run test:API
        working-directory: packages/vm

      - name: Test RLP
        run: npm run test
        working-directory: packages/rlp
