name: Node versions
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm install --frozen-lockfile

      - name: Test Block
        run: pnpm run test:node
        working-directory: packages/block

      - name: Test Blockchain
        run: pnpm run test:node
        working-directory: packages/blockchain

      # Switch client to unit tests only due to `async_hooks` dependency build error in browser tests: 2022-06-15
      - name: Test Client
        run: pnpm run test
        working-directory: packages/client

      - name: Test Devp2p
        run: pnpm run test
        working-directory: packages/devp2p

      - name: Test Common
        run: pnpm run test:node
        working-directory: packages/common

      - name: Test Ethash
        run: pnpm run test
        working-directory: packages/ethash

      - name: Test EVM
        run: pnpm run test:node
        working-directory: packages/evm

      - name: Test MPT
        run: pnpm run test:node
        working-directory: packages/mpt

      - name: Test Tx
        run: pnpm run test:node
        working-directory: packages/tx

      - name: Test Util
        run: pnpm run test:node
        working-directory: packages/util

      - name: Test StateManager
        run: pnpm run test:node
        working-directory: packages/statemanager

      - name: Test VM
        run: pnpm run test:API
        working-directory: packages/vm

      - name: Test RLP
        run: pnpm run test:node
        working-directory: packages/rlp

      - name: Test Wallet
        run: pnpm run test:node
        working-directory: packages/wallet
