name: Node versions
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16,18,20]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Test Block
        run: npm run test
        working-directory: packages/block

      - name: Test Blockchain
        run: npm run test
        working-directory: packages/blockchain

      # Switch client to unit tests only due to `async_hooks` dependency build error in browser tests: 2022-06-15
      - name: Test Client
        run: npm run test:unit
        working-directory: packages/client

      - name: Test Devp2p
        run: npm run test
        working-directory: packages/devp2p

      - name: Test Common
        run: npm run test
        working-directory: packages/common

      - name: Test Ethash
        run: npm run test
        working-directory: packages/ethash

      - name: Test EVM
        run: npm run test
        working-directory: packages/evm

      - name: Test Trie
        run: npm run test
        working-directory: packages/trie

      - name: Test Tx
        run: npm run test
        working-directory: packages/tx

      - name: Test Util
        run: npm run test
        working-directory: packages/util

      - name: Test StateManager
        run: npm run test
        working-directory: packages/statemanager

      - name: Test VM
        run: npm run test:API
        working-directory: packages/vm

      - name: Test RLP
        run: npm run test
        working-directory: packages/rlp
