# 
# This special file aims to run node tests for each relevant node version. 
# A relevant node version can be: active, current, maintenance or EOL with some months of tolerance
# For more details, please check ./scripts/node-versions.js
# 

name: Node versions
on:
  schedule:
    - cron: 0 0 * * *
    
jobs:
  get-node-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: set-matrix
        run: echo "::set-output name=matrix::$(npx testable-node-versions)"

  tests:
    needs: get-node-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node: ${{ fromJson(needs.get-node-versions.outputs.matrix) }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: npm install
      - run: npm run build

      - name: Test Block
        run: npm run test
        working-directory: packages/block

      - name: Test Blockchain
        run: npm run test
        working-directory: packages/blockchain

      - name: Test Client
        run: npm run test
        working-directory: packages/client

      - name: Test Common
        run: npm run test
        working-directory: packages/common
      
      - name: Test Devp2p
        run: npm run test
        working-directory: packages/devp2p

      - name: Test Ethash
        run: npm run test
        working-directory: packages/ethash

      - name: Test Tx
        run: npm run test
        working-directory: packages/tx

      - name: Test VM
        run: npm run test:API
        working-directory: packages/vm

