name: Tx
on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - packages/account/**
      - packages/common/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - packages/account/**
      - packages/common/**
jobs:
  test-tx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 13, 14]
    env:
      cwd: ${{github.workspace}}/packages/tx
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1

      - run: npx lerna bootstrap --scope ethereumjs-tx --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run build --scope ethereumjs-tx --include-dependencies
      - run: npx lerna run lint --scope ethereumjs-tx

      - run: npx lerna run coverage --scope ethereumjs-tx

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: tx
        if: ${{ matrix.node-version == 12 }}
