name: VM
'on':
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - packages/account/**
      - packages/block/**
      - packages/blockchain/**
      - packages/common/**
      - packages/tx/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - packages/account/**
      - packages/block/**
      - packages/blockchain/**
      - packages/common/**
      - packages/tx/**
jobs:
  test-vm-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-vm --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-vm --include-dependencies build
      - run: npm run lint
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
      - run: 'npm run test:API'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
      - run: 'npm run test:API:browser'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-vm-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-vm --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-vm --include-dependencies build
      - run: 'npm run test:state:selectedForks'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-vm-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-vm --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-vm --include-dependencies build
      - run: 'npm run test:blockchain'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
